name: "CI"
on:
  push:
    branches: "*"
  pull_request:
env:
  php-version: 8.1
  cache-version: 1
jobs:
  platform-check:
    name: "PHP 7.4 compatibility"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup PHP"
        uses: shivammathur/setup-php@2.30.3
        with:
          php-version: 7.4
          coverage: none

      - name: "Check dependency compatibility"
        run: |
          composer check-platform-reqs --no-dev

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup PHP"
        uses: shivammathur/setup-php@2.30.3
        with:
          php-version: ${{ env.php-version }}
          coverage: none

      - name: "Cache Composer dependencies"
        uses: actions/cache@v4
        with:
          path: "~/.composer/cache"
          key: composer-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('composer.json') }}
          restore-keys: |
            composer-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('composer.json') }}
            composer-dependencies-${{ runner.os }}-${{ env.cache-version }}-

      - name: "Install Composer dependencies"
        run: |
          composer -n install

      - name: "Cache NPM dependencies"
        uses: actions/cache@v4
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Build"
        run: |
          npm run build

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "build-artifact"
          path: dist

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    needs: build
    env:
      php-extensions: ast
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup PHP extension caching"
        id: extcache
        uses: shivammathur/cache-extensions@1.10.1
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.php-extensions }}
          key: php-extensions-${{ runner.os }}-${{ env.cache-version }}

      - name: "Cache extensions"
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: "Setup PHP"
        uses: shivammathur/setup-php@2.30.3
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.php-extensions }}
          coverage: none

      - name: "Cache Composer dependencies"
        uses: actions/cache@v4
        with:
          path: "~/.composer/cache"
          key: composer-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('composer.json') }}
          restore-keys: |
            composer-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('composer.json') }}
            composer-dependencies-${{ runner.os }}-${{ env.cache-version }}-

      - name: "Install Composer dependencies"
        run: |
          composer -n install

      - name: "Cache NPM dependencies"
        uses: actions/cache@v4
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Download build artifact"
        uses: actions/download-artifact@v4
        with:
          name: "build-artifact"
          path: dist

      - name: "Lint"
        run: |
          npm run lint
